In [1]:
import pandas

from util import ESConnection
from elasticsearch_dsl import Search

es_conn = ESConnection()

In [2]:
s = Search(using=es_conn, index='git')

# Unique count of Commits by Project (max 100 projects)
s.aggs.bucket('authors', 'terms', field='author_name', size=20000)\
    .metric('commits', 'cardinality', field='hash')
result = s.execute()

# In case you need to check response, uncomment line below
#print(result.to_dict()['aggregations'])

In [11]:
df = pandas.DataFrame()

df = df.from_dict(result.to_dict()['aggregations']['authors']['buckets'])
df = df.drop('doc_count', axis=1)
df['commits'] = df['commits'].apply(lambda row: row['value'])
df=df[['key', 'commits']]
df.columns = ['author', 'commits']

In [12]:
df

                                                  author  commits
0                        Hallvord Reiar Michaelsen Steen   220679
1                                         B2G Bumper Bot    50308
2                                                 GitHub    71182
3                                      Ryan VanderMeulen    19142
4                                         Cameron Dawson    23731
5                                                 Tomcat    13795
6                                    Diego Marcos Segura    14782
7                                      Robert O'Callahan    14733
8                                                KWierso    10374
9                                            David Baron    12059
10                                           bobbyholley    10166
11                                          Gaia Pushbot     9310
12                                   Nicholas Nethercote     9962
13                                                Ms2ger    12358
14                                        Jordan Santell    12434
15     Daniel Holbert [:dholbert] (away, returning Ja...     9477
16                                       Kartikaya Gupta     9089
17                                  Giorgos Logiotatidis    19074
18                                 sspitzer%netscape.com     6587
19                                                   dao     9300
20                                      bzbarsky%mit.edu     6881
21                                    alecf%netscape.com     6152
22                                           Jeff Walden     7291
23                              Mauricio Navarro Miranda    17896
24                                       Masayuki Nakano     6770
25                                        Richard Newman     8868
26                                             Myk Melez     9894
27                                             Jan de M.     6658
28                                    hyatt%netscape.com     4956
29                                   mscott%netscape.com     4767
...                                                  ...      ...
14372                                           ysangkok        1
14373                                             yscumc        1
14374                                             yuhong        1
14375                                    yusuke furukawa        1
14376                                      yutoTachibana        1
14377                                                z38        1
14378                                           z3ldaf0x        1
14379                                          zaizhuang        1
14380                                            zararah        1
14381                                          zealotous        1
14382                                         zenganshao        1
14383                                                 zn        1
14384                                          zyegfryed        1
14385                                        Éric Araujo        1
14386                                     Đặng Duy Thanh        1
14387                                       İsmail Aslan        1
14388                                     Бабин Владимир        1
14389                                   Валерий Лашманов        1
14390                                       Денис Хлякин        1
14391                                         ലാസിം ശഹദ്        1
14392                                                刘健超        1
14393                                                卢思侗        1
14394                                                孙茂胤        1
14395                                                 孟强        1
14396                                                宋晓光        1
14397                                                小奔奔        1
14398                                                徐迪行        1
14399                                                 白渐        1
14400                                                程启翔        1
14401                                               애들아빠        1

[14402 rows x 2 columns]

In [13]:
from enrich import Gender

### 'xxx' string is used here to hide gendereize key
gender = Gender(df, "xxx")
test = gender.enrich("author")

In [14]:
test

,author,commits,gender_analyzed_name,gender_probability,gender,gender_count
0,Hallvord Reiar Michaelsen Steen,220679,Hallvord,0.00,NotKnown,0
1,B2G Bumper Bot,50308,B2G,0.00,NotKnown,0
2,GitHub,71182,GitHub,0.00,NotKnown,0
3,Ryan VanderMeulen,19142,Ryan,0.99,male,4755
4,Cameron Dawson,23731,Cameron,0.94,male,614
5,Tomcat,13795,Tomcat,1.00,male,1
6,Diego Marcos Segura,14782,Diego,1.00,male,2270
7,Robert O'Callahan,14733,Robert,1.00,male,5222
8,KWierso,10374,KWierso,0.00,NotKnown,0
9,David Baron,12059,David,1.00,male,12593
10,bobbyholley,10166,bobbyholley,0.00,NotKnown,0
11,Gaia Pushbot,9310,Gaia,1.00,female,55
12,Nicholas Nethercote,9962,Nicholas,1.00,male,1176
13,Ms2ger,12358,Ms2ger,0.00,NotKnown,0
14,Jordan Santell,12434,Jordan,0.77,male,1774
15,"Daniel Holbert [:dholbert] (away, returning Ja...",9477,Daniel,1.00,male,8180
16,Kartikaya Gupta,9089,Kartikaya,0.00,NotKnown,0
17,Giorgos Logiotatidis,19074,Giorgos,0.99,male,145
18,sspitzer%netscape.com,6587,sspitzer%netscape.com,0.00,NotKnown,0
19,dao,9300,dao,0.73,female,40
20,bzbarsky%mit.edu,6881,bzbarsky%mit.edu,0.00,NotKnown,0
21,alecf%netscape.com,6152,alecf%netscape.com,0.00,NotKnown,0
22,Jeff Walden,7291,Jeff,1.00,male,2925
23,Mauricio Navarro Miranda,17896,Mauricio,1.00,male,1203
24,Masayuki Nakano,6770,Masayuki,0.80,male,5
25,Richard Newman,8868,Richard,1.00,male,4381
26,Myk Melez,9894,Myk,0.88,male,8
27,Jan de M.,6658,Jan,0.60,male,1663
28,hyatt%netscape.com,4956,hyatt%netscape.com,0.00,NotKnown,0
29,mscott%netscape.com,4767,mscott%netscape.com,0.00,NotKnown,0
...,...,...,...,...,...,...
14372,ysangkok,1,ysangkok,0.00,NotKnown,0
14373,yscumc,1,yscumc,0.00,NotKnown,0
14374,yuhong,1,yuhong,1.00,female,1
14375,yusuke furukawa,1,yusuke,1.00,male,28
14376,yutoTachibana,1,yutoTachibana,0.00,NotKnown,0
14377,z38,1,z38,0.00,NotKnown,0
14378,z3ldaf0x,1,z3ldaf0x,0.00,NotKnown,0
14379,zaizhuang,1,zaizhuang,0.00,NotKnown,0
14380,zararah,1,zararah,0.00,NotKnown,0
14381,zealotous,1,zealotous,0.00,NotKnown,0
14382,zenganshao,1,zenganshao,0.00,NotKnown,0
14383,zn,1,zn,1.00,male,1
14384,zyegfryed,1,zyegfryed,0.00,NotKnown,0
14385,Éric Araujo,1,Éric,0.00,NotKnown,0
14386,Đặng Duy Thanh,1,Đặng,1.00,female,7
14387,İsmail Aslan,1,İsmail,1.00,male,1
14388,Бабин Владимир,1,Бабин,0.00,NotKnown,0
14389,Валерий Лашманов,1,Валерий,1.00,male,6
14390,Денис Хлякин,1,Денис,1.00,male,19
14391,ലാസിം ശഹദ്,1,ലാസിം,0.00,NotKnown,0
14392,刘健超,1,刘健超,0.00,NotKnown,0
14393,卢思侗,1,卢思侗,0.00,NotKnown,0
14394,孙茂胤,1,孙茂胤,0.00,NotKnown,0
14395,孟强,1,孟强,0.00,NotKnown,0
14396,宋晓光,1,宋晓光,0.00,NotKnown,0
14397,小奔奔,1,小奔奔,0.00,NotKnown,0
14398,徐迪行,1,徐迪行,0.00,NotKnown,0
14399,白渐,1,白渐,0.00,NotKnown,0
14400,程启翔,1,程启翔,0.00,NotKnown,0
14401,애들아빠,1,애들아빠,0.00,NotKnown,0

## Contributors by Gender

Number of people by gender is shown below. We use [Genderize API](https://genderize.io/) to infer gender based on first name. For those cases in which gender can't be identified, 'NotKnown' string is used.

In [15]:
copy_test = test.copy()

In [17]:
gender = copy_test.groupby("gender")

In [23]:
gender.count()["author"]

gender
NotKnown    5044
female       780
male        8578
Name: author, dtype: int64

In [24]:
test.to_csv('gender_mozilla.csv')